---
name: badboy
web: "https://fnordig.de"
twitter: "badboy_"
avatar: "https://secure.gravatar.com/avatar/dd016fe8d3b2f44d2c9c5f3367b3ad25.png"
events:
  - year: 2012
    events:
      - "NoSQL Matters CGN"
      - 29c3
  - year: 2013
    events:
      - FrOSCon
      - "RailsCamp Germany"
      - 30c3
  - year: 2014
    events:
      - FOSDEM
      - {name: "OpenTechSchool - HTML & CSS for beginners", role: "Coach"}
      - {name: "OpenTechSchool - Javascript for beginners", role: "Coach"}
      - eurucamp
      - {name: "FrOSCon / RedFrog Conf", role: "Speaker"}
      - "JSConf EU"
      - reject.js
      - "RailsCamp Germany"
      - {name: 'Barcamp "The Next Web" Salzburg', role: "Coach"}
      - "IETF 91"
      - 31c3
  - year: 2015
    events:
      - FOSDEM
      - ".concat()"
      - {name: "otsconf", role: "Organizer"}
      - "Redis Developer Day London"
      - {name: "Hungarian Web Conference", role: "Speaker"}
      - 32c3
  - year: 2016
    events:
      - RuhrJS
      - {name: "View Source", role: "Coach" }
      - {name: "RustFest", role: "Organizer"}
